curso/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from autenticacao import views as autentic
app_name = 'curso'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('', listar_cursos, name='listar_cursos'),
    path('curso/<int:curso_id>/disciplinas/', listar_disciplinas_curso, name='listar_disciplinas_curso'),
    path('projetos/', listar_projetos_disciplinas, name='listar_projetos_disciplinas'),
    path('projeto/<int:projeto_id>/', detalhes_projeto, name='detalhes_projeto'),
    path('docentes/', listar_docentes, name='listar_docentes'),
    path('disciplina/editar/<int:disciplina_id>/', editar_disciplina, name='editar_disciplina'),

    path('login/', autentic.login_user, name='login'),
    path('logout/', autentic.logout_user, name='logout'),

    path('<str:site>/login/', autentic.login_user_withredirect, name = 'login_redirect'),
    path('<str:site>/logout/', autentic.logout_user_withredirect, name = 'logout_redirect'),

    path('docente/editar/<int:docente_id>/', editar_docente, name='editar_docente'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


app_name = 'index'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meusite.urls')),  # novo path
    path('noobsite/', include('noobsite.urls')),  # novo path
    path('pwsite/', include('pwsite.urls')),  # novo path
    path('novaapp/', include('novaapp.urls')),  # novo path
    path('bandas/', include('bandas.urls')),  # novo path
    path('artigos/', include('artigos.urls')),  # novo path
    path('curso/', include('curso.urls')),  # novo path
    path('festivais/', include('festivais.urls')),  # novo path
    path('musicas/', include('musicas.urls')),  # novo path
    path('meteo/', include('meteo.urls')),  # novo path

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

curso/models.py
from django.db import models

# Create your models here.
class Curso(models.Model):
    nome = models.CharField(max_length=100)
    apresentacao = models.TextField()
    objetivos = models.TextField()
    competencias = models.TextField()
    disciplinas = models.ManyToManyField("Disciplina")

    def __str__(self):
        return self.nome

class AreaCientifica(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Disciplina(models.Model):
    nome = models.CharField(max_length=100)
    ano = models.IntegerField()
    semestre = models.IntegerField()
    ects = models.IntegerField()
    curricularIUnitReadableCode = models.CharField(max_length=100)
    area_cientifica = models.ForeignKey(AreaCientifica, on_delete=models.CASCADE)
    projetos = models.ManyToManyField("Projeto")

    def __str__(self):
        return self.nome

class Projeto(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    conceitos_aplicados = models.TextField()
    tecnologias_usadas = models.TextField()
    #disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class LinguagemProgramacao(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Docente(models.Model):
    nome = models.CharField(max_length=100)
    disciplinas = models.ManyToManyField(Disciplina)

    def __str__(self):
        return self.nome

curso/forms.py
from django import forms
from .models import *

class DisciplinaForm(forms.ModelForm):
    class Meta:
        model = Disciplina
        fields = ['nome', 'ano', 'semestre', 'ects', 'curricularIUnitReadableCode', 'area_cientifica', 'projetos']

class DocenteForm(forms.ModelForm):
    class Meta:
        model = Docente
        fields = ['nome', 'disciplinas']

curso/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . import views
from .models import *
from .forms import *
from django.db.models import Count
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.

def index_view(request):
    return listar_cursos(request)

@login_required
def editar_disciplina(request, disciplina_id):
    disciplina = get_object_or_404(Disciplina, pk=disciplina_id)
    if request.method == 'POST':
        form = DisciplinaForm(request.POST, instance=disciplina)
        if form.is_valid():
            form.save()
            return redirect('curso:listar_disciplinas_curso', curso_id=disciplina.curso.id)
    else:
        form = DisciplinaForm(instance=disciplina)
    return render(request, 'curso/editar_disciplina.html', {'form': form})

@login_required
def editar_docente(request, docente_id):
    docente = get_object_or_404(Docente, pk=docente_id)
    if request.method == 'POST':
        form = DocenteForm(request.POST, instance=docente)
        if form.is_valid():
            form.save()
            return redirect('curso:listar_docentes')
    else:
        form = DocenteForm(instance=docente)
    return render(request, 'curso/editar_docente.html', {'form': form})


def listar_cursos(request):
    cursos = Curso.objects.all()
    context = {
        'cursos': cursos
    }
    return render(request, 'curso/curso.html', context)

def listar_disciplinas_curso(request, curso_id):
    curso = Curso.objects.get(id=curso_id)
    disciplinas = Curso.objects.get(id=curso_id).disciplinas.annotate(num_projetos = Count('projetos')).order_by('ano', '-num_projetos')
    context = {
        'curso': curso,
        'disciplinas': disciplinas
    }
    return render(request, 'curso/disciplinas.html', context)

def detalhes_projeto(request, projeto_id):
    projeto = get_object_or_404(Projeto, id=projeto_id)
    context = {
        'projeto': projeto
    }
    return render(request, 'curso/detalhes_projeto.html', context)

def password_reset(request):
    # Sua lógica de recuperação de senha aqui
    return render(request, 'curso/password_reset.html')

def password_reset_done(request):
    # Sua lógica de recuperação de senha feita aqui
    return render(request, 'curso/password_reset_done.html')

def password_reset_confirm(request, uidb64, token):
    # Sua lógica de confirmação de recuperação de senha aqui
    return render(request, 'curso/password_reset_confirm.html')

def password_reset_complete(request):
    # Sua lógica de recuperação de senha completa aqui
    return render(request, 'curso/password_reset_complete.html')

def listar_docentes(request):
    docentes = Docente.objects.all()
    context = {
        'docentes': docentes
    }
    return render(request, 'curso/docentes.html', context)

def listar_projetos_disciplinas(request):
    projetos = Projeto.objects.all()
    context = {
        'projetos': projetos
    }
    return render(request, 'curso/projeto.html', context)

curso/templates/curso/curso.html
{% extends 'curso/layout.html' %}

{% block title %}
Lista de Cursos
{% endblock %}

{% block content %}
<h1>Lista de Cursos</h1>
<ul>
    {% for curso in cursos %}
    <li>
        {{ curso.nome }}
        <ul>
            <li><a href="{% url 'curso:listar_disciplinas_curso' curso.id %}">Disciplinas</a></li>
            <br>
            <h3>Apresentação: </h3> <li>
                {{ curso.apresentacao }} </li>
            <br>
            <h3>Objetivos: </h3><li>{{ curso.objetivos }}</li>
            <br>
            <h3>Competências: </h3><li> {{ curso.competencias }} </li>
        </ul>
    </li>
    {% endfor %}
</ul>
{% endblock %}

curso/templates/curso/detalhes_projeto.html
{% extends 'curso/layout.html' %}

{% block title %}
Detalhes do Projeto: {{ projeto.nome_projeto }}
{% endblock %}

{% block content %}
<h1>Detalhes do Projeto: {{ projeto.nome_projeto }}</h1>
<ul>
    <li>Descrição: {{ projeto.descricao }}</li>
    <li>Conceitos Aplicados: {{ projeto.conceitos_aplicados }}</li>
    <li>Tecnologias Usadas: {{ projeto.tecnologias_usadas }}</li>
</ul>
{% endblock %}

curso/templates/curso/disciplinas.html
{% extends 'curso/layout.html' %}

{% block title %}
Disciplinas do Curso: {{ curso.nome }}
{% endblock %}

{% block content %}
<h1>Disciplinas do Curso: {{ curso.nome }}</h1>
<ul>
    {% for disciplina in disciplinas %}
    <li>{{ disciplina.nome }}
        {% if user.is_authenticated %}
            <a href="{% url 'curso:editar_disciplina' disciplina.id %}"><button>Editar</button></a></li>
        {% endif %}
    <ul>
        <li>Ano: {{ disciplina.ano }}</li>
        <br>
        <li>Semestre: {{ disciplina.semestre }}</li>
        <br>
        <li>ECTS: {{ disciplina.ects }}</li>
        <br>
        <li>Curricular IUnit Readable Code: {{ disciplina.curricularIUnitReadableCode }}</li>
        <br>
        <li>Área Científica: {{ disciplina.area_cientifica.nome }}</li>
        <br>
        <li>Projetos:</li>
        <ul>
            {% for projeto in disciplina.projetos.all %}
            <li><a href="{% url 'curso:detalhes_projeto' projeto.id %}">{{ projeto.nome }}</a></li>
            <br>
            {% endfor %}
        </ul>
    </ul>
    <br>
    {% endfor %}
</ul>
{% endblock %}

curso/templates/curso/docentes.html
{% extends 'curso/layout.html' %}

{% block title %}
Lista de Docentes
{% endblock %}

{% block content %}
<h1>Lista de Docentes</h1>
<ul>
    {% for docente in docentes %}
    <li>
        {{ docente.nome }}
        {% if user.is_authenticated %}
            <a href="{% url 'curso:editar_docente' docente.id %}"><button>Editar</button></a></li>
        {% endif %}
    </li>
    <ul>
        <li>Disciplinas:
            <ul>
                {% for disciplina in docente.disciplinas.all %}
                    <li>{{ disciplina.nome }}</li>
                {% endfor %}
            </ul>
        </li>
    </ul>
    <br>
    {% endfor %}
</ul>
{% endblock %}

curso/templates/curso/editar_disciplina.html
{% extends 'curso/layout.html' %}

{% block title %}
Editar Disciplina
{% endblock %}

{% block content %}
    <h1>Editar Disciplina</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Salvar</button>
    </form>
{% endblock %}

curso/templates/curso/editar_docente.html
{% extends 'curso/layout.html' %}

{% block title %}
Editar Docente
{% endblock %}

{% block content %}
<h1>Editar Docente</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>
{% endblock %}

curso/templates/curso/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>📜 Cursos 📜</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/css-curso.css' %}">
</head>
<body>
    <header>
        <h1>📜 Cursos 📜</h1>
    </header>
    <main>
        <nav>
            {% if user.is_authenticated %}
                <div class="user-box">
                    Bem-vindo, {{ user.username }}
                </div>
                <br>
                <br>
                <a href="{% url 'curso:listar_cursos' %}">Cursos</a>
                <a href="{% url 'curso:listar_docentes' %}">Docentes</a>
                <a href="{% url 'curso:logout' %}" class='red'>Logout</a>
            {% else %}
                <a href="{% url 'curso:listar_cursos' %}">Cursos</a>
                <a href="{% url 'curso:listar_docentes' %}">Docentes</a>
                <a href="{% url 'curso:login' %}" class='green'>Login</a>
            {% endif %}
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>
</html>

curso/templates/curso/password_reset.html
{% extends 'curso/layout.html' %}

{% block title %}
Recuperação de Senha
{% endblock %}

{% block content %}
<h2>Recuperação de Senha</h2>
<form method="post">
    {% csrf_token %}
    <p>Por favor, insira seu endereço de e-mail abaixo. Você receberá um link para criar uma nova senha via e-mail.</p>
    <label for="id_email">Endereço de E-mail:</label><br>
    <input type="email" id="id_email" name="email"><br><br>
    <button type="submit">Enviar E-mail de Recuperação</button>
</form>
{% endblock %}

curso/templates/curso/password_reset_complete.html
{% extends 'curso/layout.html' %}

{% block title %}
Recuperação de Senha Concluída
{% endblock %}

{% block content %}
<h2>Recuperação de Senha Concluída</h2>
<p>Sua senha foi redefinida com sucesso. Você pode agora <a href="{% url 'login' %}">fazer login</a> com sua nova senha.</p>
{% endblock %}

curso/templates/curso/password_reset_confirm.html
{% extends 'curso/layout.html' %}

{% block title %}
Confirmação de Recuperação de Senha
{% endblock %}

{% block content %}
<h2>Confirmação de Recuperação de Senha</h2>
<form method="post">
    {% csrf_token %}
    <label for="id_new_password1">Nova Senha:</label><br>
    <input type="password" id="id_new_password1" name="new_password1"><br>
    <label for="id_new_password2">Confirme a Nova Senha:</label><br>
    <input type="password" id="id_new_password2" name="new_password2"><br><br>
    <button type="submit">Salvar Nova Senha</button>
</form>
{% endblock %}

curso/templates/curso/password_reset_done.html
{% extends 'curso/layout.html' %}

{% block title %}
Recuperação de Senha Enviada
{% endblock %}

{% block content %}
<h2>Recuperação de Senha Enviada</h2>
<p>Um e-mail com instruções para redefinir sua senha foi enviado para o seu endereço de e-mail.</p>
{% endblock %}

curso/templates/curso/projeto.html
{% extends 'curso/layout.html' %}

{% block title %}
Projetos das Disciplinas
{% endblock %}

{% block content %}
<h1>Projetos das Disciplinas</h1>
<ul>
    {% for projeto in projetos %}
    <li>Nome do Projeto: {{ projeto.nome_projeto }}</li>
    <ul>
        <li>Descrição: {{ projeto.descricao }}</li>
        <br>
        <li>Conceitos Aplicados: {{ projeto.conceitos_aplicados }}</li>
        <br>
        <li>Tecnologias Usadas: {{ projeto.tecnologias_usadas }}</li>
        <br>
        <li>Disciplina: {{ projeto.disciplina.nome }}</li>
        <br>
    </ul>
    {% endfor %}
</ul>
{% endblock %}