bandas/urls.py
from django.urls import path
from . import views  # importamos views para poder usar as suas funções
from autenticacao import views as autentic

app_name = 'bandas'

urlpatterns = [
    path('', views.index_view, name='index'),

    # Mostrar busca
    path('<str:tipo>/<int:nome_data>', views.show_view, name='show'),

    # Mostrar todas
    path('<str:tipo>/', views.show_all_view, name='show_all'),

    # Editar
    path('<str:tipo>/edit/<int:id_data>', views.edit_view, name='edit'),

    path('apagar/<str:tipo>', views.apagar_view, name='apagar'),
    path('apagar/<str:tipo>/<int:id_data>', views.apagar, name='apagar_data'),


    path('inserir/<str:tipo>', views.insert_view, name = 'inserir'),

    path('login/', autentic.login_user, name = 'login'),
    path('logout/', autentic.logout_user, name = 'logout'),
]

curso/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from autenticacao import views as autentic
app_name = 'curso'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('', listar_cursos, name='listar_cursos'),
    path('curso/<int:curso_id>/disciplinas/', listar_disciplinas_curso, name='listar_disciplinas_curso'),
    path('projetos/', listar_projetos_disciplinas, name='listar_projetos_disciplinas'),
    path('projeto/<int:projeto_id>/', detalhes_projeto, name='detalhes_projeto'),
    path('docentes/', listar_docentes, name='listar_docentes'),
    path('disciplina/editar/<int:disciplina_id>/', editar_disciplina, name='editar_disciplina'),

    path('login/', autentic.login_user, name='login'),
    path('logout/', autentic.logout_user, name='logout'),

    path('<str:site>/login/', autentic.login_user_withredirect, name = 'login_redirect'),
    path('<str:site>/logout/', autentic.logout_user_withredirect, name = 'logout_redirect'),

    path('docente/editar/<int:docente_id>/', editar_docente, name='editar_docente'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

meusite/urls.py
from django.urls import path, include
from . import views  # importamos views para poder usar as suas funções
from django.contrib.auth import views as auth_views
from autenticacao import views as autentic

app_name = 'meusite'

urlpatterns = [
    path('trabalhos/', views.trabalhos_view, name='trabalhos'),
    path('aboutme/', views.aboutme_view, name='aboutme'),
    path('faculdade/', views.faculdade_view, name='faculdade'),
    path('admin-tools/', views.admin_view, name='admin'),
    path('', views.index_view, name='index'),


    path('login/', autentic.login_user, name = 'login'),
    path('logout/', autentic.logout_user, name = 'logout'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


app_name = 'index'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meusite.urls')),  # novo path
    path('noobsite/', include('noobsite.urls')),  # novo path
    path('pwsite/', include('pwsite.urls')),  # novo path
    path('novaapp/', include('novaapp.urls')),  # novo path
    path('bandas/', include('bandas.urls')),  # novo path
    path('artigos/', include('artigos.urls')),  # novo path
    path('curso/', include('curso.urls')),  # novo path
    path('festivais/', include('festivais.urls')),  # novo path
    path('musicas/', include('musicas.urls')),  # novo path
    path('meteo/', include('meteo.urls')),  # novo path

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

bandas/models.py
from django.db import models

class Banda(models.Model):
    nome = models.CharField(max_length=100)
    foto = models.ImageField(upload_to='bandas', blank=True)
    album = models.ManyToManyField('Album', blank=True)

    def __str__(self):
        return self.nome

class Album(models.Model):
    nome = models.CharField(max_length=100)
    capa = models.ImageField(upload_to='albuns', blank=True)
    musicas = models.ManyToManyField('Musica', blank=True)

    def __str__(self):
        return self.nome

class Musica(models.Model):
    titulo = models.CharField(max_length=100)
    link = models.URLField(blank=True)
    foto = models.ImageField(upload_to='musicas', blank=True)
    biografia = models.CharField(max_length=1000, null = True, blank = True)

    def __str__(self):
        return self.titulo

bandas/forms.py
from django import forms
from .models import *

class BandaForm(forms.ModelForm):
    class Meta:
        model = Banda
        fields = ['nome', 'foto', 'album']

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['nome', 'capa', 'musicas']

class MusicaForm(forms.ModelForm):
    class Meta:
        model = Musica
        fields = ['titulo', 'link', 'foto', 'biografia']
        help_texts = { 'biografia': '<br>Insira uma breve biografia de 4-5 linhas.',
                        'titulo': '<br>Escreva o titulo da musica',
                        'link': '<br>Insira o link da musica',
                        'foto': '<br>Inserir Imagem',
                    }

bandas/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required

# Create your views here.

def index_view(request):
    return show_all_view(request, 'banda')

#show
def show_view(request, tipo, nome_data):
    if tipo == 'album':
        data = Album.objects.get(id= nome_data)

    elif tipo == 'musica':
        data = Musica.objects.get(id= nome_data)

    else:
        data = Banda.objects.get(id = nome_data)

    content = {
        'tipo': tipo,
        'data': data,
        'id': nome_data
    }

    return render(request, "bandas/show.html", content)

# all
def show_all_view(request, tipo):
    if tipo == 'album':
        data = Album.objects.all().order_by('nome')

    elif tipo == 'musica':
        data = Musica.objects.all().order_by('titulo')

    else:
        data = Banda.objects.all().order_by('nome')

    context = {
        'tipo': tipo,
        'data': data,
    }
    return render(request, "bandas/show_all.html", context)

# Edit
@login_required
def edit_view(request, id_data, tipo):
    if tipo == "banda":
        data = Banda.objects.get(id = id_data)

        content = {
            'data': data,
            'tipo': tipo,
        }

        if request.method == 'POST':
            form = BandaForm(request.POST, request.FILES, instance=data)
            if form.is_valid():
                form.save()
                return redirect('bandas:show', tipo= 'banda', nome_data = id_data)
        else:
            form = BandaForm(instance=data)
        content['form'] = form

        return render(request, 'bandas/edit.html', content)

    elif tipo == "album":
        data = Album.objects.get(id = id_data)
        content = {
            'data': data,
            'tipo': tipo,
        }

        if request.method == 'POST':
            form = AlbumForm(request.POST, request.FILES, instance=data)
            if form.is_valid():
                form.save()
                return redirect('bandas:show', tipo= 'album', nome_data = id_data)
        else:
            form = AlbumForm(instance=data)
        content['form'] = form
        return render(request, 'bandas/edit.html', content)

    elif tipo == "musica":
        data = Musica.objects.get(id = id_data)
        content = {
            'data': data,
            'tipo': tipo,
        }

        if request.method == 'POST':
            form = MusicaForm(request.POST, request.FILES, instance=data)
            if form.is_valid():
                form.save()
                return redirect('bandas:show', tipo= 'musica', nome_data = id_data)
        else:
            form = MusicaForm(instance=data)

        content['form'] = form
        return render(request, 'bandas/edit.html', content)

    else:
        return redirect('bandas:bandas')

#inserir
@login_required
def insert_view(request, tipo):

    content = {
        'tipo':tipo,
    }

    if request.method == 'POST':
        if tipo == 'banda':
            nome_banda = request.POST.get('nome_banda')
            banda = Banda.objects.create(nome=nome_banda)
            return redirect('bandas:show', 'banda', banda.id)  # Redirecionar para uma página de sucesso

        elif tipo == 'album':
            nome_album = request.POST.get('nome_album')
            album = Album.objects.create(nome=nome_album)
            return redirect('bandas:show', 'album', album.id)  # Redirecionar para uma página de sucesso

        elif tipo == 'musica':
            titulo_musica = request.POST.get('titulo_musica')
            musica = Musica.objects.create(titulo=titulo_musica)
            return redirect('bandas:show', 'musica', musica.id)  # Redirecionar para uma página de sucesso

    # Passando o tipo para o contexto do template
    return render(request, 'bandas/insert.html', content)

#apagar
@login_required
def apagar_view(request, tipo):
    if tipo == 'album':
        context = {
            'tipo':'album',
            'data': Album.objects.all().order_by('nome'),
        }
        return render(request, "bandas/apagar.html", context)

    elif tipo == 'musica':
        context = {
            'tipo':'musica',
            'data': Musica.objects.all().order_by('titulo'),
        }
        return render(request, "bandas/apagar.html", context)

    elif tipo == 'banda':
        context = {
            'tipo':'banda',
            'data': Banda.objects.all().order_by('nome'),
        }
        return render(request, "bandas/apagar.html", context)

    else:
        render(request, "bandas/layout.html")

#funcoes
@login_required
def apagar(request, id_data, tipo):
    if tipo == 'banda':
        instance = get_object_or_404(Banda, id=id_data)
    elif tipo == 'album':
        instance = get_object_or_404(Album, id=id_data)
    elif tipo == 'musica':
        instance = get_object_or_404(Musica, id=id_data)
    else:
        # Handle invalid type
        return redirect('')  # Redirect to appropriate page

    # Delete the instance
    instance.delete()

    # Redirect to appropriate page
    if tipo == 'banda':
        return redirect('bandas:show_all', 'banda')

    elif tipo == 'album':
        return redirect('bandas:show_all', 'album')

    elif tipo == 'musica':
        return redirect('bandas:show_all', 'musica')

bandas/templates/bandas/apagar.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <p>Existe(m) {{ data|length }} banda(s):</p>
    <ul class="buttons">
    {% for banda in data %}
        <li>
            {{banda}}<a href="{% url 'bandas:apagar_data' banda.id tipo %}">

            <button class='remove'>Apagar</button></a>
        </li>
    {% endfor %}
    </ul>
    <br>
    <br>
{% endblock %}

bandas/templates/bandas/edit.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h1>Editar {{tipo}}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Salvar</button>
    </form>
    <a href="{% url 'bandas:apagar_data' tipo data.id %}"><button class="remove" >Apagar</button></a>
{% endblock %}

bandas/templates/bandas/insert.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h1>Inserir {{tipo}}</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="tipo" value="{{ tipo }}">

        {% if tipo == 'banda' %}
            <label for="nome_banda">Nome da Banda:</label>
            <input type="text" id="nome_banda" name="nome_banda" required>

        {% elif tipo == 'album' %}
            <label for="nome_album">Nome do Álbum:</label>
            <input type="text" id="nome_album" name="nome_album" required>

        {% elif tipo == 'musica' %}
            <label for="titulo_musica">Título da Música:</label>
            <input type="text" id="titulo_musica" name="titulo_musica" required>

        {% endif %}

        <input type="submit" value="Enviar">
    </form>

{% endblock %}

bandas/templates/bandas/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🎵 Bandas 🎵</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css-banda.css' %}">
</head>
<body>
    <header>
        <h1>🎵 Bandas 🎵</h1>
        <nav id="nav-menu" class="nav-menu">
            <div>
                <a href="{% url 'bandas:show_all' 'banda' %}">Bandas</a>
                <a href="{% url 'bandas:show_all' 'album' %}">Albuns</a>
                <a href="{% url 'bandas:show_all' 'musica' %}">Musicas</a>

                {% if user.is_authenticated %}
                    <a href="{% url 'meusite:logout' %}" class='red'>Logout</a>
                {% else %}
                    <a href="{% url 'meusite:login' %}" class='green'>Login</a>
                {% endif %}
            </div>
        </nav>
    </header>
    <button id="menu-toggle" class="menu-toggle">&#9776;</button>
    <main>
        <section>
            {% block content %}
            {% endblock %}
        </section>
    </main>
    <footer>
        <p>&copy; 2024 Programação Web, Universidade Lusófona - Todos os direitos reservados.</p>
    </footer>

    <script>
        // JavaScript para alternar a visibilidade do menu
        document.getElementById('menu-toggle').addEventListener('click', function() {
            document.getElementById('nav-menu').classList.toggle('active');
        });

        document.addEventListener('scroll', function() {
            const menuToggle = document.getElementById('menu-toggle');
            if (window.scrollY > 0) {
                menuToggle.classList.add('scrolled');
            } else {
                menuToggle.classList.remove('scrolled');
            }
        });

    </script>
</body>
</html>

bandas/templates/bandas/show.html
{% extends 'bandas/layout.html' %}

{% block content %}
{{ nome }}
{% if tipo == 'banda' %}
    <h3>{{ data }}</h3>
    {% if data.foto %}
        <img src='{{ data.foto.url }}' width="150px">
    {% else %}
        <p>Sem imagem!</p>
    {% endif %}

    <h3>Albuns:</h3>
    <ul class="buttons">
        {% for album in data.album.all|dictsort:"nome" %}
            <li>
                <a href="{% url 'bandas:show' 'album' album.id %}">
                    <button class="data_button">{{ album }}</button>
                </a>
            </li>
        {% endfor %}
    </ul>
    {% if data.album.all|length <= 0 %}
        <p>A banda ainda não possui albuns!</p>
    {% endif %}
    <br><br>
    {% if user.is_authenticated %}
        {% if user.is_superuser %}
            <a href="{% url 'bandas:edit' 'banda' id %}">
                <button class="button">Editar Banda</button>
            </a>
        {% endif %}
    {% endif %}

{% elif tipo == 'album' %}
    <h3>Album: {{ data.nome }}</h3>
    {% if data.capa %}
        <img src='{{ data.capa.url }}' width="150px">
    {% else %}
        <p>Sem imagem!</p>
    {% endif %}

    <h3>Lista de músicas do álbum:</h3>
    <ul class="buttons">
        {% for musica in data.musicas.all|dictsort:"titulo" %}
            <li><a href="{% url 'bandas:show' 'musica' musica.id %}"><button class="data_button">{{ musica }}</button></a></li>
        {% endfor %}
    </ul>
    {% if data.musicas.all|length <= 0 %}
        <p>O Album ainda não possui musicas!</p>
    {% endif %}
    <br><br>
    {% if user.is_authenticated %}
        {% if user.is_superuser %}
            <a href="{% url 'bandas:edit' tipo='album' id_data=data.id %}"><button class="button">Editar Álbum</button></a>
        {% endif %}
    {% endif %}

{% elif tipo == 'musica' %}
    <h3>Música: {{ data }}  </h3>
    {% if data.foto %}
        <img src='{{ data.foto.url }}' width="150px">
    {% else %}
        <p>Sem imagem!</p>
    {% endif %}


    <h3>Biografia:</h3>
    {% if data.biografia != None %}
        <p class="biografia">{{ data.biografia}} </p>
    {% else %}
        <p>Sem Biografia!</p>
    {% endif %}

    <h3>Link:
    <br>
    {% if data.link != "" %}
        <a href="{{ data.link }}" target="_blank"><button class="data_button">Ouvir</button></a>
    {% else %}
        <p>Sem Link!</p>
    {% endif %}
    </h3>

    <br>
    {% if user.is_authenticated %}
        {% if user.is_superuser %}
            <a href="{% url 'bandas:edit' 'musica' data.id %}"><button class="button">Editar Música</button></a>
        {% endif %}
    {% endif %}
{% endif %}
{% endblock %}

bandas/templates/bandas/show_all.html
{% extends 'bandas/layout.html' %}

{% block content %}
    {% if tipo == 'banda' %}
        <p>Existe(m) {{ data|length }} banda(s):</p>
        <ul class="buttons">
        {% for banda in data %}
            <li>
                <a href="{% url 'bandas:show' 'banda' banda.id %}"><button  class="data_button">{{ banda }}</button></a>
            </li>
        {% endfor %}
        </ul>
        <br>
        <br>
        {% if user.is_authenticated %}
            {% if user.is_superuser %}
                <a href="{% url 'bandas:inserir' 'banda' %}"><button>Inserir Banda</button></a>
            {% endif%}
        {% endif%}

    {% elif tipo == 'album' %}
        <p>Existe(m) {{ data|length }} album(ns):</p>
        <ul class="buttons">
        {% for album in data %}
            <li>
                <a href="{% url 'bandas:show' 'album' album.id %}"><button  class="data_button">{{ album }}</button></a>
            </li>
        {% endfor %}
        </ul>
        <br>
        <br>
        {% if user.is_authenticated %}
            {% if user.is_superuser %}
                <a href="{% url 'bandas:inserir' 'album' %}"><button>Inserir Album</button></a>
            {% endif%}
        {% endif%}

    {% elif tipo == 'musica' %}
        <p>Existe(m) {{ data|length }} musica(s):</p>
        <ul class="buttons">
        {% for musica in data %}
            <li>
                <a href="{% url 'bandas:show' 'musica' musica.id %}"><button  class="data_button">{{ musica }}</button></a>
            </li>
        {% endfor %}
        </ul>
        <br>
        <br>
        {% if user.is_authenticated %}
            {% if user.is_superuser %}
               <a href="{% url 'bandas:inserir' 'musica' %}"><button>Inserir Musica</button></a>
            {% endif%}
        {% endif%}
    {% endif %}
{% endblock %}