curso/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from autenticacao import views as autentic
app_name = 'curso'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('', listar_cursos, name='listar_cursos'),
    path('curso/<int:curso_id>/disciplinas/', listar_disciplinas_curso, name='listar_disciplinas_curso'),
    path('projetos/', listar_projetos_disciplinas, name='listar_projetos_disciplinas'),
    path('projeto/<int:projeto_id>/', detalhes_projeto, name='detalhes_projeto'),
    path('docentes/', listar_docentes, name='listar_docentes'),
    path('disciplina/editar/<int:disciplina_id>/', editar_disciplina, name='editar_disciplina'),

    path('login/', autentic.login_user, name='login'),
    path('logout/', autentic.logout_user, name='logout'),

    path('<str:site>/login/', autentic.login_user_withredirect, name = 'login_redirect'),
    path('<str:site>/logout/', autentic.logout_user_withredirect, name = 'logout_redirect'),

    path('docente/editar/<int:docente_id>/', editar_docente, name='editar_docente'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

meteo/urls.py
from django.urls import path, include
from . import views  # importamos views para poder usar as suas funções
from django.contrib.auth import views as auth_views
from autenticacao import views as autentic

app_name = 'meteo'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('<int:id>/<int:dia>', views.city_dia_view, name='hoje'),
    path('<int:id>/', views.city_view, name='cidade'),

    path('login/', autentic.login_user, name = 'login'),
    path('logout/', autentic.logout_user, name = 'logout'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


app_name = 'index'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meusite.urls')),  # novo path
    path('noobsite/', include('noobsite.urls')),  # novo path
    path('pwsite/', include('pwsite.urls')),  # novo path
    path('novaapp/', include('novaapp.urls')),  # novo path
    path('bandas/', include('bandas.urls')),  # novo path
    path('artigos/', include('artigos.urls')),  # novo path
    path('curso/', include('curso.urls')),  # novo path
    path('festivais/', include('festivais.urls')),  # novo path
    path('musicas/', include('musicas.urls')),  # novo path
    path('meteo/', include('meteo.urls')),  # novo path

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

meteo/models.py
from django.db import models

# Create your models here.

meteo/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import requests
from datetime import datetime, timedelta


# Create your views here.
def index_view(request):
    global_id = 1110600 # ID para Lisboa
    url = f"https://api.ipma.pt/open-data/forecast/meteorology/cities/daily/{global_id}.json"
    response = requests.get(url)
    data = response.json()
    url = "https://api.ipma.pt/open-data/distrits-islands.json"

    # Fazendo a requisição GET
    response = requests.get(url)

    # Verificando se a requisição foi bem-sucedida
    if response.status_code == 200:
        # Convertendo a resposta para JSON
        localidades = response.json().get('data', [])  # Acessa a chave 'data' se existir
        localidades_lista = [
            {"id": localidade['globalIdLocal'], "nome": localidade['local']}
            for localidade in localidades
        ]
    else:
        localidades_lista = []

    nome = ""
    for localidade in localidades_lista:
        if localidade['id'] == global_id:
            nome = localidade['nome']
            break

    for day in data['data']:
        if(day["idWeatherType"] >= 10):
            day["idWeatherType"] = "imagens/w_ic_d_" + str(day["idWeatherType"]) + ".svg"
        else:
            day["idWeatherType"] = "imagens/w_ic_d_0" + str(day["idWeatherType"]) + ".svg"

    context = {
        'city': nome,
        'weather': data['data'],
        'localidades': localidades_lista,
        'id': int(1110600),
    }

    return render(request, "meteo/index.html", context)

def city_dia_view(request, id, dia):
    global_id = id  # ID para Lisboa
    url = f"https://api.ipma.pt/open-data/forecast/meteorology/cities/daily/{global_id}.json"
    response = requests.get(url)
    data = response.json()

    url = "https://api.ipma.pt/open-data/distrits-islands.json"

    # Fazendo a requisição GET
    response = requests.get(url)

    # Verificando se a requisição foi bem-sucedida
    if response.status_code == 200:
        # Convertendo a resposta para JSON
        localidades = response.json().get('data', [])

        # Preparando a lista de localidades
        localidades_lista = [
            {"id": localidade['globalIdLocal'], "nome": localidade['local']}
            for localidade in localidades
        ]

        nome = ""
        for localidade in localidades_lista:
            if localidade['id'] == id:
                nome = localidade['nome']
                break
    else:
        localidades_lista = []
        nome = ""



    if(data['data'][dia]["idWeatherType"] >= 10):
        data['data'][dia]["idWeatherType"] = "imagens/w_ic_d_" + str(data['data'][dia]["idWeatherType"]) + ".svg"
    else:
        data['data'][dia]["idWeatherType"] = "imagens/w_ic_d_0" + str(data['data'][dia]["idWeatherType"]) + ".svg"



    context = {
        'city': nome,
        'day': data['data'][dia],
        'dia':dia,
        'filename': data['data'][dia]["idWeatherType"],
        'localidades': localidades_lista,
        'id': id,
    }


    return render(request, "meteo/day.html", context)


def city_view(request, id):
    global_id = id  # ID para Lisboa
    url = f"https://api.ipma.pt/open-data/forecast/meteorology/cities/daily/{global_id}.json"
    response = requests.get(url)
    data = response.json()


    url = "https://api.ipma.pt/open-data/distrits-islands.json"

    # Fazendo a requisição GET
    response = requests.get(url)

    # Verificando se a requisição foi bem-sucedida
    if response.status_code == 200:
        # Convertendo a resposta para JSON
        localidades = response.json().get('data', [])  # Acessa a chave 'data' se existir
        localidades_lista = [
            {"id": localidade['globalIdLocal'], "nome": localidade['local']}
            for localidade in localidades
        ]
    else:
        localidades_lista = []

    nome = ""
    for localidade in localidades_lista:
        if localidade['id'] == id:
            nome = localidade['nome']
            break




    for day in data['data']:
        if(day["idWeatherType"] >= 10):
            day["idWeatherType"] = "imagens/w_ic_d_" + str(day["idWeatherType"]) + ".svg"
        else:
            day["idWeatherType"] = "imagens/w_ic_d_0" + str(day["idWeatherType"]) + ".svg"

    context = {
        'city': nome,
        'weather': data['data'],
        'localidades': localidades_lista,
        'id': int(id),
    }

    return render(request, "meteo/index.html", context)

meteo/templates/meteo/day.html
{% extends 'meteo/layout.html' %}
{% load static %}
{% block title %} {{ city }} {% endblock %}

{% block header %}
    <header><h1> {{ city }} </h1></header>
{% endblock %}

{% block nav %}
    <nav id="nav-menu" class="nav-menu">
        <div>
            <div class="scroll"> <!-- Corrigido: class="scroll" -->
                {% for localidade in localidades %}
                    <a href="{% url 'meteo:cidade' localidade.id %}" class = "center">{{ localidade.nome }}</a>
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
                <a href="{% url 'curso:logout' %}" class='red'>Logout</a>
            {% else %}
                <a href="{% url 'curso:login' %}" class='green'>Login</a>
            {% endif %}
        </div>
    </nav>
{% endblock %}


{% block content %}
    <section>
        <a href="{% url 'meteo:hoje' id dia%}"><button>Recarregar</button></a>
        <h1>Previsão do Tempo para {{ city }}</h1>
        <hr>
        {% if day %}
            <h2>{{ day.forecastDate }} <img src = "{% static filename %}"></h2>
            <p><b>Máxima:</b> {{ day.tMax }}°C</p>
            <p><b>Mínima:</b> {{ day.tMin }}°C</p>
            <p><b>Precipitação:</b> {{ day.precipitaProb }}%</p>
            <b>Vento:</b>
            <ul class= "buttons">
                <li><b>  Direção:</b> {{ day.predWindDir }}</li>
                <li><b>  Velocidade:</b> {{ day.classWindSpeed }} km/h</li>
            </ul>
        {% else %}
            <p>Dados não disponíveis.</p>
        {% endif %}
        <hr>
    </section>
{% endblock %}

meteo/templates/meteo/index.html
{% extends 'meteo/layout.html' %}
{% load static %}
{% block title %} {{ city }} {% endblock %}

{% block header %}
    <header><h1> {{ city }} </h1></header>
{% endblock %}

{% block nav %}
    <nav id="nav-menu" class="nav-menu">
        <div>
            <div class="scroll"> <!-- Corrigido: class="scroll" -->
                {% for localidade in localidades %}
                    <a href="{% url 'meteo:cidade' localidade.id %}" class = "center">{{ localidade.nome }}</a>
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
                <a href="{% url 'curso:logout' %}" class='red'>Logout</a>
            {% else %}
                <a href="{% url 'curso:login' %}" class='green'>Login</a>
            {% endif %}
        </div>
    </nav>
{% endblock %}

{% block content %}
    <section>
        <a href="{% url 'meteo:hoje' id 0%}"><button>Hoje</button></a>
        <a href="{% url 'meteo:index'%}"><button>Recarregar</button></a>
        {% if weather%}
            <h1>Previsão do Tempo para {{ city }}</h1>
            <hr>
            {% for day in weather%}
                {% if day %}
                    <h2>{{ day.forecastDate }} <img src="{% static day.idWeatherType %}"></h2>
                    <p><b>Máxima:</b> {{ day.tMax }}°C</p>
                    <p><b>Mínima:</b> {{ day.tMin }}°C</p>
                    <p><b>Probabilidade de Precipitação:</b> {{ day.precipitaProb }}%</p>
                    <b>Vento:</b>
                    <ul class= "buttons">
                        <li><p><b>  Direção:</b> {{ day.predWindDir }}</p></li>
                        <li><p><b>  Velocidade:</b> {{ day.classWindSpeed }} km/h</p></li>
                    </ul>
                {% else %}
                    <p>Dados não disponíveis.</p>
                {% endif %}
                <hr>
            {% endfor %}
        {% else %}
            Sem info;
        {% endif%}
    </section>
{% endblock %}

meteo/templates/meteo/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>☀️Metereologia️🌧️</title>
    <title>{% block title %} {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css-meteo.css' %}">
</head>
<body>
    {% block header %}{% endblock %}

    {% block nav %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    <button id="menu-toggle" class="menu-toggle">&#9776;</button>

    <script>
        // JavaScript para alternar a visibilidade do menu
        document.getElementById('menu-toggle').addEventListener('click', function() {
            document.getElementById('nav-menu').classList.toggle('active');
        });

        document.addEventListener('scroll', function() {
            const menuToggle = document.getElementById('menu-toggle');
            if (window.scrollY > 0) {
                menuToggle.classList.add('scrolled');
            } else {
                menuToggle.classList.remove('scrolled');
            }
        });

    </script>
</body>
</html>