curso/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from autenticacao import views as autentic
app_name = 'curso'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('', listar_cursos, name='listar_cursos'),
    path('curso/<int:curso_id>/disciplinas/', listar_disciplinas_curso, name='listar_disciplinas_curso'),
    path('projetos/', listar_projetos_disciplinas, name='listar_projetos_disciplinas'),
    path('projeto/<int:projeto_id>/', detalhes_projeto, name='detalhes_projeto'),
    path('docentes/', listar_docentes, name='listar_docentes'),
    path('disciplina/editar/<int:disciplina_id>/', editar_disciplina, name='editar_disciplina'),

    path('login/', autentic.login_user, name='login'),
    path('logout/', autentic.logout_user, name='logout'),

    path('<str:site>/login/', autentic.login_user_withredirect, name = 'login_redirect'),
    path('<str:site>/logout/', autentic.logout_user_withredirect, name = 'logout_redirect'),

    path('docente/editar/<int:docente_id>/', editar_docente, name='editar_docente'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

meusite/urls.py
from django.urls import path, include
from . import views  # importamos views para poder usar as suas funções
from django.contrib.auth import views as auth_views
from autenticacao import views as autentic

app_name = 'meusite'

urlpatterns = [
    path('trabalhos/', views.trabalhos_view, name='trabalhos'),
    path('aboutme/', views.aboutme_view, name='aboutme'),
    path('faculdade/', views.faculdade_view, name='faculdade'),
    path('admin-tools/', views.admin_view, name='admin'),
    path('', views.index_view, name='index'),


    path('login/', autentic.login_user, name = 'login'),
    path('logout/', autentic.logout_user, name = 'logout'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


app_name = 'index'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meusite.urls')),  # novo path
    path('noobsite/', include('noobsite.urls')),  # novo path
    path('pwsite/', include('pwsite.urls')),  # novo path
    path('novaapp/', include('novaapp.urls')),  # novo path
    path('bandas/', include('bandas.urls')),  # novo path
    path('artigos/', include('artigos.urls')),  # novo path
    path('curso/', include('curso.urls')),  # novo path
    path('festivais/', include('festivais.urls')),  # novo path
    path('musicas/', include('musicas.urls')),  # novo path
    path('meteo/', include('meteo.urls')),  # novo path

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

meusite/models.py
from django.db import models
from django.urls import reverse

class Tipo(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Trabalho(models.Model):
    nome = models.CharField(max_length=100)
    url = models.CharField(max_length=100)  # Change CharField to URLField
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse(self.url)

meusite/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from random import randint



def download_template():
    # URL do template do Canva
    canva_url = "https://www.canva.com/design/DAGCaKpqcBA/V9xgU03RIOccfSNa6ybY8Q/view"

    # Solicita o conteúdo do Canva
    response = requests.get(canva_url)

    # Retorna o conteúdo como um arquivo PDF
    return send_file(response.content, mimetype='application/pdf', as_attachment=True, attachment_filename='meu_template.pdf')


def get_frase():
    frases = [
        "Bem-vindo ao meu portfólio! Explore meu trabalho e descubra mais sobre mim.",
        "Olá! Fico feliz em vê-lo aqui. Navegue pelo site e conheça meus projetos.",
        "Seja bem-vindo! Sinta-se à vontade para explorar minhas criações.",
        "Bem-vindo ao meu espaço criativo! Espero que goste do que verá.",
        "Olá e bem-vindo! Aqui você encontrará um pouco sobre minha jornada e meus trabalhos.",
        "Bem-vindo! Agradeço sua visita e espero que se inspire com meus projetos.",
        "Seja bem-vindo ao meu portfólio online! Fique à vontade para explorar e entrar em contato.",
        "Olá! Obrigado por visitar meu site. Explore minhas obras e saiba mais sobre mim.",
        "Bem-vindo! Confira meus trabalhos e projetos recentes aqui.",
        "Seja bem-vindo ao meu cantinho na web! Aproveite para conhecer um pouco mais sobre meu trabalho.",
    ]
    frase = frases[randint(0,len(frases)-1)]
    return frase

def index_view(request):


    context = {'frase': get_frase()}
    return render(request, "meusite/index.html", context)

def aboutme_view(request):
    return render(request, "meusite/aboutme.html")

@login_required
def admin_view(request):
    return render(request, "meusite/admin.html")

def trabalhos_view(request):
    sites = Tipo.objects.get(nome='Pessoal/sites')
    programas = Tipo.objects.get(nome='Pessoal/programas')
    context = {
        'programas': Trabalho.objects.filter(tipo=programas.id).order_by('nome'),
        'sites': Trabalho.objects.filter(tipo=sites.id).order_by('nome')
    }

    return render(request, "meusite/trabalhos.html", context)

def faculdade_view(request):
    sites = Tipo.objects.get(nome='Faculdade/sites')
    programas = Tipo.objects.get(nome='Faculdade/programas')
    context = {
        'programas': Trabalho.objects.filter(tipo=programas.id).order_by('nome'),
        'sites': Trabalho.objects.filter(tipo=sites.id).order_by('nome')
    }
    return render(request, "meusite/faculdade.html", context)

meusite/templates/meusite/aboutme.html
{% extends 'meusite/layout.html' %}
{% block header %}Sobre Mim{% endblock %}
{% block content %}
    <section style="padding: 0px 20px 20px 20px;">
        <div style="position: relative; width: 100%; height: 0; padding-top: 141.4286%;
         padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
         border-radius: 8px; will-change: transform;">
          <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
            src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGCaKpqcBA&#x2F;V9xgU03RIOccfSNa6ybY8Q&#x2F;view?embed">
          </iframe>
        </div>
        <button class = "download" onclick="downloadPDF()">Download</button>
    </section>
    

    <script>
        function downloadPDF() {
            // Substitua 'seu_pdf.pdf' pelo nome do seu PDF no diretório 'static'
            var pdfPath = '/static/CV_Bernardo_ildefonso.pdf';
            var link = document.createElement('a');
            link.href = pdfPath;
            link.download = 'CV_Bernardo_ildefonso.pdf';
            link.click();
        }
    </script>
{% endblock %}

meusite/templates/meusite/admin.html
{% extends 'meusite/layout.html' %}
{% block header %}Admin{% endblock %}

{% block content %}
    <!-- Site -->
    <section>
        <h2>Ferramentas de Admin:</h2>
        <ul class="buttons">
            <li><a href="/admin/" target="_blank"><button class='data_button'>Admin</button></a></li>
            <li><a href = 'https://www.pythonanywhere.com' target="_blank"><button class='data_button'>PythonAnywere</button></a></li>
        </ul>
    </section>
{% endblock %}

meusite/templates/meusite/faculdade.html
{% extends 'meusite/layout.html' %}
{% block header %}Faculdade{% endblock %}

{% block content %}
    <!-- Site -->
    <section>
        <p>Programas:</p>
            <ul class="buttons">
                {% for trabalho in programas %}
                    <li><a href="{{ trabalho.get_absolute_url }}" target="_blank"><button class="data_button">{{ trabalho.nome }}</button></a></li>
                {% endfor %}
            </ul>

            <p>Sites:</p>
            <ul class="buttons">
                {% for trabalho in sites %}
                    <li><a href="{{ trabalho.get_absolute_url }}" target="_blank"><button class="data_button">{{ trabalho.nome }}</button></a></li>
                {% endfor %}
            </ul>

    </section>
{% endblock %}

meusite/templates/meusite/index.html
{% extends 'meusite/layout.html' %}
{% block header %}Inicio{% endblock %}

{% block content %}
    <section>
        <h1>{{frase}}</h1>
    </section>
{% endblock %}

meusite/templates/meusite/layout.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🦊Bernardo Ildefonso🦊️</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css-site.css' %}">
</head>
<body>
    <header>
        <center><h3>{% block header %} {% endblock %}</h3></center>
        <!-- Barra de navegação -->
        <nav id="nav-menu" class="nav-menu">
            <div>
                <a href="/">Início</a>
                <a href="{% url 'meusite:aboutme' %}">Sobre Mim</a>
                <a href="{% url 'meusite:trabalhos' %}">Trabalhos</a>
                <a href="{% url 'meusite:faculdade' %}">Faculdade</a>
                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <a href="{% url 'meusite:admin' %}" class='admin'>Admin</a>
                    {% endif %}
                {% endif %}
                {% if user.is_authenticated %}
                    <a href="{% url 'curso:logout' %}" class='red'>Logout</a>
                {% else %}
                    <a href="{% url 'curso:login' %}" class='green'>Login</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <main>
        {% block content %}
        <!-- Conteúdo do site que será organizado em grid -->
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Bernardo Ildefonso</p>
    </footer>

    <button id="menu-toggle" class="menu-toggle">&#9776;</button>

    <script>
        // JavaScript para alternar a visibilidade do menu
        document.getElementById('menu-toggle').addEventListener('click', function() {
            document.getElementById('nav-menu').classList.toggle('active');
        });

        document.addEventListener('scroll', function() {
            const menuToggle = document.getElementById('menu-toggle');
            if (window.scrollY > 0) {
                menuToggle.classList.add('scrolled');
            } else {
                menuToggle.classList.remove('scrolled');
            }
        });
    </script>
</body>
</html>

meusite/templates/meusite/login.html
{% extends 'meusite/layout.html' %}
{% block header %}Login{% endblock %}


{% block title %}Login{% endblock %}
{% block content %}
    <section>
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            <label for="username">Username:</label><br>
            <input type="text" id="username" name="username"><br>
            <label for="password">Password:</label><br>
            <input type="password" id="password" name="password"><br><br>
            <input type="submit" value="Login">
        </form>
        <br>
        <!-- <a href="{% url 'meusite:password_reset' %}"><button>Esqueceu sua senha?</button></a> -->
    </section>
{% endblock %}

meusite/templates/meusite/trabalhos.html
{% extends 'meusite/layout.html' %}
{% block header %}Trabalhos{% endblock %}

{% block content %}
    <section>
        <p>Programas:</p>
        <ul class="buttons">
            {% for trabalho in programas %}
                <li><a href="{{ trabalho.get_absolute_url }}" target="_blank"><button class="data_button">{{ trabalho.nome }}</button></a></li>
            {% endfor %}
        </ul>

        <p>Sites:</p>
        <ul class="buttons">
            {% for trabalho in sites %}
                <li><a href="{{ trabalho.get_absolute_url }}" target="_blank"><button class="data_button">{{ trabalho.nome }}</button></a></li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}